FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist .
EXPOSE 5173
CMD ["npx", "http-server", "-p 5173", "/app"] 
