name: Dockerfile Standard Checks
on:
  push:
    branches: [ main ]  
jobs:
  build:
    uses: deriv-iac/shared-actions/.github/workflows/deriv-ci.yml@master
    with:
      images: jothimanideriv/ghaction-poc
      project_type: skip
      dockerfile: "./Dockerfile"
