name: Dockerfile Standard Checks

on:
  push:
    branches: [ node ]

jobs:
  standard-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check and build docker Image
        uses: suyash-deriv/dockerfile-action@main
        with:
          images: suyashderiv/sample-node-app
          push: true
          dockerfile: './nodetest/Dockerfile.dev'
          context: './nodetest'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_password }}
          project_type: 'node'
