name: Dockerfile Standard Checks

on:
  push:
    branches: [ main ]
  

jobs:
  standard-checks:  
    name: Check and build docker Image
    uses: deriv-iac/shared-actions/.github/workflows/deriv-ci.yml@master
    with:
      images: suyashderiv/sample-app
      project_type: skip
