name: Dockerfile Standard Checks

on:
  push:
    branches: [ main ]

jobs:
  standard-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check and Docker Image
        uses: suyash-deriv/dockerfile-action@v0.1
