name: Dockerfile Standard Checks

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    uses: deriv-iac/shared-actions/.github/workflows/deriv-ci.yml@master
    with:
      images: suyashderiv/sample-app
      project_type: skip
      dockerfile: "./Dockerfile"
